openapi: 3.0.3
info:
  title: Scrabble Toolkit RESTful API
  version: 0.1.0
  
components:
    schemas:
      TileSet:
        type: object
        properties:
          language:
            type: string
            example: en
          tiles:
            type: object
            additionalProperties:
              type: object
              properties:
                points:
                  type: integer
                count:
                  type: integer
            example:
              A:
                points: 1
                count: 9
              B:
                points: 3
                count: 2
              C:
                points: 3
                count: 2
      EnrichedWord:
        type: object
        properties:
          word:
            type: string
            example: apple
          definition: 
            type: string
            example: an edible fruit [n APPLES]
          alphagram:
            type: string
            example: AELPP
          frontHooks:
            type: string[]
            example: ['D']
          backHooks:
            type: string[]
            example: ['S', 'T', 'Y']
          value:
            type: number
            example: 10
          wordListName:
            type: string
            example: NWL2023
          tilsetName:
            type: string
            example: EN_STANDARD

tags:
  - name: Tile Sets
  - name: Enriched Words
    
paths:
  /api/tilesets:
    get:
      summary: Retrieve all available Scrabble tile sets.
      tags:
        - Tile Sets
      responses:
        200:
          description: Successful response. Returns an array of Scrabble tile sets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TileSet'

  /api/tilesets/name/{name}:
    get:
      summary: Retrieves a Scrabble tile set by its name.
      tags:
        - Tile Sets
      parameters:
        - name: name
          in: path
          description: The name of the Scrabble tile set to retrieve.
          required: true
          schema:
            type: string
          example: EN_STANDARD
      responses:
        200:
          description: Successful response. Returns a single Scrabble tile set object.
          content:
            application/json:
              schema:
                $ref: '#components/schemas/TileSet'
        404:
          description: Tile set not found for the provided name.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating the error.
              example:
                message: Scrabble tile set not found for name '{name}'.

  /api/tilesets/language/{language}:
    get:
      summary: Retrieves all Scrabble tile sets for the specified language.
      tags:
        - Tile Sets
      parameters:
        - name: language
          in: path
          description: The language code for the desired tile sets to retrieve (ISO 639-1).
          required: true
          schema:
            type: string
          example: en
      responses:
        200:
          description: Successful response. Returns an array of Scrabble tile sets.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TileSet'
        400:
          description: Invalid request. This error occurs when the language parameter is not a valid ISO 639-1 code.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating the error.
              example:
                message: Language parameter must be a valid ISO 639-1 code.

  /api/enrichedwords/{wordListName}/{tileSetName}/{pattern}:
    get:
      summary: Finds a word in a specific word list using the specified tile set.
      tags:
        - Enriched Words
      parameters:
        - name: wordListName
          in: path
          description: The name of the word list where to look for the word.
          required: true
          schema:
            type: string
          example: NWL2023
        - name: tileSetName
          in: path
          description: The name of the tile set used to enrich the words.
          required: true
          schema:
            type: string
          example: EN_STANDARD
        - name: pattern
          in: path
          description: The word/pattern to search.
          required: true
          schema:
            type: string
          example: APPLE
      responses:
        200:
            description: Successful response. Returns an enriched word.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/EnrichedWord'
        404:
          description: Enriched word not found for the provided parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating the error.
              example:
                message: "Word 'ZXRT' not found inside 'NWL2023' word list using 'EN_STANDARD' tile set."
        400:
          description: Invalid request. This error occurs when the language parameter is not a valid ISO 639-1 code.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating the error.
              example:
                message: "'validatePattern' query parameter is required"
  /api/enrichedwords/anagrams/{wordListName}/{tileSetName}/{pattern}:
    get:
      summary: Finds anagrams of a word in a specified word list using the specified tile set.
      tags:
        - Enriched Words
      parameters:
        - name: wordListName
          in: path
          description: The name of the word list where to look for the anagrams.
          required: true
          schema:
            type: string
          example: NWL2023
        - name: tileSetName
          in: path
          description: The name of the tile set used to enrich the words.
          required: true
          schema:
            type: string
          example: EN_STANDARD
        - name: pattern
          in: path
          description: The letters to be used in the search.
          required: true
          schema:
            type: string
          example: TAC
      responses:
        200:
          description: Successful response. Returns an array of enriched words.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EnrichedWord'
                example:
                  - word: "ACT"
                    definition: "to do something [v ACTED, ACTING, ACTS]"
                    alphagram: "ACT"
                    frontHooks: "FPT"
                    backHooks: "AS"
                    value: 5
                    wordListName: "NWL2023"
                    tileSetName: "EN_STANDARD"
                  - word: "CAT"
                    definition: "to hoist an anchor to the cathead [v CATS, CATTED, CATTING]"
                    alphagram: "ACT"
                    frontHooks: "S"
                    backHooks: "EHS"
                    value: 5
                    wordListName: "NWL2023"
                    tileSetName: "EN_STANDARD"
        400:
          description: Invalid request. This error occurs when the language parameter is not a valid ISO 639-1 code.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating the error.
              example:
                message: "'validatePattern' query parameter is required"
